// <auto-generated />
namespace PhotoGallery.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updatedPhotoController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedPhotoController));
        
        string IMigrationMetadata.Id
        {
            get { return "201503300001144_updatedPhotoController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
